# Generated by Django 2.2.1 on 2019-07-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_task_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
    ]
